### ISSUE TITLE
Allow commands to not have arguments

### ISSUE THREAD

**Issue by chrisparsons83** [chrisparsons83/RedditFFDiscordBot#1]
When running a command without an argument, no message will be returned due to how we parse messages for commands and arguments.

```
.8ball
```

doesn't return anything.

```
.8ball testing
```

will return a message.

**Comment by tc216997** [comment]
The new discord API dont allow empty argument i believe. If the argument after the command is empty, it will return the command as string.

**Comment by chrisparsons83** [comment]
Are you still seeing an error on this? I just ran !8ball and saw the error message I'd expect to see.

If you aren't seeing it either on your end, feel free to close this issue out.

**Comment by chrisparsons83** [comment]
This appears to be working, we should be good now.
