### ISSUE TITLE
Team Depth at Position

### ISSUE THREAD

**Issue by IceMaine** [chrisparsons83/RedditFFDiscordBot#14]
If possible, it would be nice to be able to do something like:
!depth [team] [position]

e.g.
!depth ATL RB

Returns:
Devonta Freeman
Tevin Coleman
Terron Ward

Possible sources:
http://www.ourlads.com/nfldepthcharts/depthchartpos/RB
https://www.cbssports.com/nfl/teams/depth-chart/ATL/atlanta-falcons
http://subscribers.footballguys.com/apps/depthchart.php
http://www.nfl.com/teams/chicagobears/depthchart?team=ATL

**Comment by tc216997** [comment]
Just finished writing this function. Test it out when the pull request is merged.

**Comment by chrisparsons83** [comment]
Merged that feature, we do need to tweak the arguments a bit and just trim the two strings we pull out, otherwise we'll get " WR" instead of "WR". I can grab it tonight unless you want to grab it sooner.
